### ISSUE TITLE
The solution is not working on Android when the link is opened from Chrome browser

### ISSUE THREAD

**Issue by OrceMih** [hampusohlsson/browser-deeplink#2]
On Android the provided solution is not working, when you open the link from Chrome app.
The app is not redirecting to the Google Play, even though the appId is correct.
When i open the link from the default browser, it works ok.

On iOS the both cases (with Safari and Chrome) are working good.

**Comment by hampusohlsson** [comment]
I have not been able to confirm this issue as I do not have access to any Android device. If anyone has the possibility to help out it would be greatly appreciated!

**Comment by hampusohlsson** [comment]
Need help to verify this is working in Chrome on Android now.

**Comment by OrceMih** [comment]
I just checked on two Android devices (Samsung Note 4 and Nexus 6), the browser redirects to the app on the Google Play, which means that the problem is fixed.

**Comment by hampusohlsson** [comment]
Great, thanks!
